### PR TITLE
Add support for solaris - fix #69

### LINKED ISSUE #69: Building on Illumos Issue
Illumos doesn't have sys call.Flock. Could we please use syscall.FcntlFlock ?
```
# code.gitea.io/git/vendor/gopkg.in/src-d/go-billy.v4/osfs
../git/vendor/gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:13:9: undefined: syscall.Flock
../git/vendor/gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:13:41: undefined: syscall.LOCK_EX
../git/vendor/gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:20:9: undefined: syscall.Flock
../git/vendor/gopkg.in/src-d/go-billy.v4/osfs/os_posix.go:20:41: undefined: syscall.LOCK_UN
```

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>
Fixes https://github.com/src-d/go-billy/issues/69

### CODE REVIEW

**Comment by fkorotkov** [comment]
@mcuadros gentle ping. 😅Working on Solaris support for Cirrus CI and would love to see this merged since our agent uses `go-git` for cloning which depends on `go-billy`.

**Comment by mcuadros** [comment]
https://github.com/src-d/go-billy/releases/tag/v4.3.1

**Comment by fkorotkov** [comment]
@mcuadros greatly appreciate it! 🙌

**Comment by fkorotkov** [comment]
Hey @kuba--, does seem like this change fixed the issue of building for Solaris. Could you please take a look at #71 where I've also added tests for building binaries for supported platforms.

**Pull request merged**
