### PR TITLE
add Exists method.

### PR DESCRIPTION
**Pull request by smola**
Exists is a convenience method to check if a file exists in a
Filesystem.

### CODE REVIEW

**Comment by Serabe** [comment]
LGTM

**Comment by smola** [comment]
@alcortesm I would say that checking the existence of a file is pretty useful ;-)

The implementation of this function is the common pattern of checking existence with Stat+IsNotExist. We use this pattern in quite a few places (e.g. in go-git, checking if a path contains a git repository or not), so we're not introducing any weird behavior. We're not splitting anything. not exists error of subsequent calls (e.g. Open, Rename, etc) should still be handled as usual. Having a shortcut for Stat+IsNotExist does not change that.

**Comment by alcortesm** [comment]
Not sure of the current state of this, maybe we need more people commenting on this.

**Comment by smola** [comment]
@alcortesm I'm closing this myself. I was getting functions from our old implementations into go-billy, so I'll reopen this issue if we need this when we migrate old code to go-billy.

**Pull request closed without merging**
