### PR TITLE
memfs refactor

### PR DESCRIPTION
**Pull request by mcuadros**
memfs, had some issue related to how handled the dirs. 

This reactor change the way of the implementation handles the dirs, creating the dirs when a file is created.
Improve the performance as well of the legibility of the code.

### CODE REVIEW

**Comment by mcuadros** [comment]
I merged the PR by accident, setting the Windows testing sorry, please review it anyway.

**Comment by alcortesm** [comment]
Can you explain the issues related with how we handle dirs before and why this PR fixes them?

**Comment by mcuadros** [comment]
The main problem was that a dir was inferred by an existent file and wasn't created it self when the file was created. So for example when you delete the file the directory doesn't exists anymore.

Also I found some bugs, so I added the test and refactored it because was a complete mess. Now the dir is created when a file is created exactly as osfs does.

**Comment by alcortesm** [comment]
I see, thanks!

**Pull request merged**
